version: "3.8"
services:
  peoplecounter:
    build: .
    image: peoplecounter:latest
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - .:/workspace
      - //dev/video0:/dev/video0  # notation Windows
    privileged: true
    tty: true
    shm_size: "1g"
